"""Added bon and produit tables

Revision ID: e5136ab285fd
Revises: ebc0d6244061
Create Date: 2025-07-03 15:14:48.181556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5136ab285fd'
down_revision: Union[str, None] = 'ebc0d6244061'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fournisseur', sa.String(length=100), nullable=False),
    sa.Column('contact', sa.String(length=64), nullable=False),
    sa.Column('montant', sa.Integer(), nullable=False),
    sa.Column('paid', sa.Boolean(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('produits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bon_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bon_id'], ['bons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('produits')
    op.drop_table('bons')
    # ### end Alembic commands ###
